sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0.0

env:
  global:
    - ROLES=[admin, user]
  matrix:
    - DB=postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database merciedgar_test;' -U postgres
  - bundle exec rake db:create db:migrate db:seed

addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 8850bccc6911d74965627b1fafe753beb368fab00d33de0c7576c6598fc1220e

script:
  - bundle exec rake db:seed spec

notifications:
  slack: merciedgar:HYdsoJI3d26VzdKgQYvMguWX
