# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
development:
  MANDRILL_USERNAME: dev@merciedgar.com
  MANDRILL_API_KEY: cGexDJKQdMR684K1s9x4Og
  MAILCHIMP_API_KEY: ad5ab5a0c2bf57ea770e60d109b0ea93-us7
  MAILCHIMP_LIST_ID: 24957
  ADMIN_NAME: Christophe Robillard
  ADMIN_EMAIL: christophe@merciedgar.com
  ADMIN_PASSWORD: MrcxloP1
  ROLES: [admin, user]
  EMAIL_ADDRESS: dev@merciedgar.com
  DOMAIN: www.merciedgar.com

staging:
  MANDRILL_USERNAME: staging@merciedgar.com
  MANDRILL_API_KEY: cGexDJKQdMR684K1s9x4Og
  MAILCHIMP_API_KEY: 564be3b15f85b50665fc1b219bc0dd5d-us7
  MAILCHIMP_LIST_ID: 30645
  ADMIN_NAME: Christophe Robillard
  ADMIN_EMAIL: christophe@merciedgar.com
  ADMIN_PASSWORD: MrcxloP1
  ROLES: [admin, user]
  EMAIL_ADDRESS: staging@merciedgar.com
  DOMAIN: staging.merciedgar.com
