config: &config
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost

development:
  database: merciedgar
  username: merciedgar
  password: PstxloP1
  <<: *config

test: &test
  database: merciedgar_test
  username: merciedgar
  password: PstxloP1
  <<: *config

production:
  database: merciedgar_prod
  username: merciedgar
  password: PstxloP1
  <<: *config

cucumber:
  <<: *test
